* Wat was het lastigste om uit te vinden of te maken?
Het uitvinden van werken en updaten van de database was de lastigste taak tot nu toe. Ik gebruik de api key van tmdb zo dat er telkens gekeken wordt of de data in eigen database zit. Zoniet, slaat hij de opgevraagde tmdb info op in mijn iamddb database.
Dit kostte onverwacht veel energie.
* Waar en waarom ben je afgeweken van het oorspronkelijke ontwerp?
Ik heb besloten mijn website minimaler te maken dan mijn oorspronkelijke ontwerp. Dit is nog niet te zien aangezien ik vooral met het opzetten van database bezig ben geweest.
* Wat is er nog onzeker aan het project en hoe ga je dit uitzoeken?
Het is nog onzeker hoe de website eruit gaat zien. Dit laat ik nog een beetje open. Maar voor episodes, kan je dus per season zeggen t/m welke episode je hebt gekeken of wil kijken. Ik weet nog niet helemaal hoe ik dit ga vormgeven.
* Wat is het eerstvolgende waar je aan gaat werken en waarom?
De database zal eind van de week klaar zijn, daarna ga ik beginnen aan serie paginas opzetten en watched list maken. 
* Ontbreekt er nog iets fundamenteels, bijvoorbeeld omdat het lastiger was dan verwacht, of dat een alternatief toch handiger is? Beschrijf dan kort wat er aan de hand is.
Er ontbreekt nog de functie van lijsten maken, films in je watched en to watch list zetten. Verder ontbreekt er nog design van de pagina's.
